slang_general = {
    "7an": "tujuan",
    "@": "di",
    "ababil": "abg labil",
    "abis": "habis",
    "acc": "accord",
    "ad": "ada",
    "adlah": "adalah",
    "adlh": "adalah",
    "adoh": "aduh",
    "afaik": "as far as i know",
    "aha": "tertawa",
    "ahaha": "haha",
    "ahokncc": "ahok",
    "aing": "saya",
    "aj": "saja",
    "aja": "saja",
    "ajep-ajep": "dunia gemerlap",
    "ajj": "saja",
    "ak": "saya",
    "aka": "dikenal juga sebagai",
    "akhirx": "akhirnya",
    "akika": "aku",
    "akko": "aku",
    "akkoh": "aku",
    "akku": "aku",
    "akuwh": "aku",
    "akyu": "aku",
    "alay": "norak",
    "aljasa": "asal jadi saja",
    "alow": "halo",
    "ama": "sama",
    "ambilin": "ambilkan",
    "ambl": "ambil",
    "analisise": "analisis",
    "ancur": "hancur",
    "anjir": "anjing",
    "anjrit": "anjing",
    "ank": "anak",
    "anter": "antar",
    "ap": "apa",
    "ap2": "apa-apa",
    "apaan": "apa",
    "apasih": "apa sih",
    "ape": "apa",
    "apes": "sial",
    "aplot": "unggah",
    "aps": "apa",
    "apva": "apa",
    "aq": "saya",
    "aqu": "aku",
    "aquwh": "aku",
    "asap": "sesegera mungkin",
    "asbun": "asal bunyi",
    "aseek": "asyik",
    "aseekk": "asyik",
    "asek": "asyik",
    "asekk": "asyik",
    "aseknya": "asyiknya",
    "asem": "asam",
    "asoy": "asyik",
    "aspal": "asli tetapi palsu",
    "astrojim": "astagfirullahaladzim",
    "astul": "asal tulis",
    "ath": "kalau begitu",
    "ato": "atau",
    "atuh": "kalau begitu",
    "au ah": "tidak mau tahu",
    "ava": "avatar",
    "awak": "saya",
    "aws": "awas",
    "ay": "sayang",
    "ayang": "sayang",
    "ayank": "sayang",
    "ayok": "ayo",
    "b4": "sebelum",
    "bacot": "banyak bicara",
    "bakalan": "akan",
    "bales": "balas",
    "bandes": "bantuan desa",
    "bangdes": "pembangunan desa",
    "bangedh": "banget",
    "bangkotan": "tua",
    "banpol": "bantuan polisi",
    "banpres": "bantuan presiden",
    "banpur": "bantuan tempur",
    "bansarkas": "bantuan sarana kesehatan",
    "basbang": "basi",
    "bazis": "badan amal, zakat, infak, dan sedekah",
    "bcanda": "bercanda",
    "bcoz": "karena",
    "bdg": "bandung",
    "beb": "sayang",
    "begajulan": "nakal",
    "bejibun": "banyak",
    "beliin": "belikan",
    "belom": "belum",
    "benarjujur": "jujur",
    "bencong": "banci",
    "bener": "benar",
    "bentar": "sebentar",
    "ber2": "berdua",
    "ber3": "bertiga",
    "berdikari": "berdiri di atas kaki sendiri",
    "beresin": "membereskan",
    "bet": "banget",
    "bete": "bosan",
    "beti": "beda tipis",
    "beud": "banget",
    "beut": "banget",
    "bg": "abang",
    "bgd": "banget",
    "bgmn": "bagaimana",
    "bgs": "bagus",
    "bgt": "banget",
    "bgtt": "banget",
    "bgttt": "banget",
    "bhubu": "tidur",
    "bijimane": "bagaimana",
    "bimbuluh": "bimbingan dan penyuluhan",
    "bintal": "bimbingan mental",
    "bisi": "kalau-kalau",
    "bkl": "akan",
    "bkn": "bukan",
    "bknnya": "bukannya",
    "bl": "beli",
    "blegug": "bodoh",
    "blg": "bilang",
    "blh": "boleh",
    "blm": "belum",
    "bln": "bulan",
    "bls": "balas",
    "blum": "belum",
    "bnchi": "benci",
    "bnci": "benci",
    "bngung": "bingung",
    "bnran": "yang benar",
    "bnyk": "banyak",
    "bodor": "lucu",
    "bohay": "badan aduhai",
    "bokap": "ayah",
    "bokep": "porno",
    "boker": "buang air besar",
    "bokin": "pacar",
    "bokis": "bohong",
    "bole": "boleh",
    "boljug": "boleh juga",
    "bolot": "bodoh",
    "bonek": "bocah nekat",
    "bonyok": "ayah ibu",
    "boyeh": "boleh",
    "bpk": "bapak",
    "br": "baru",
    "brb": "segera kembali",
    "brg": "bareng",
    "brngkt": "berangkat",
    "bro": "saudara laki-laki",
    "brp": "berapa",
    "bru": "baru",
    "brur": "saudara laki-laki",
    "bs": "bisa",
    "bsa": "bisa",
    "bsen": "bosan",
    "bsk": "besok",
    "bt": "buat",
    "btw": "ngomong-ngomong",
    "bu_bu": "tidur",
    "buangbuang": "buang",
    "buaya": "tidak setia",
    "bubarin": "bubarkan",
    "bubbu": "tidur",
    "buber": "buka bersama",
    "bubu": "tidur",
    "bujubune": "luar biasa",
    "bumil": "ibu hamil",
    "buser": "buru sergap",
    "bw": "bawa",
    "bwhn": "bawahan",
    "bwt": "buat",
    "byar": "bayar",
    "byk": "banyak",
    "byr": "bayar",
    "byrin": "bayarkan",
    "c8": "chat",
    "cabal": "sabar",
    "cabut": "pergi",
    "cadas": "keren",
    "caem": "cakep",
    "calo": "makelar",
    "cama-cama": "sama-sama",
    "can": "belum",
    "cangcut": "celana dalam",
    "capcus": "pergi",
    "cape": "capek",
    "caper": "cari perhatian",
    "caur": "jelek",
    "cb": "coba",
    "ce": "cewek",
    "cekak": "tidak ada uang",
    "cekal": "cegah tangkal",
    "cekidot": "coba lihat",
    "cemen": "penakut",
    "cemplungin": "cemplungkan",
    "cengengesan": "tertawa",
    "ceper": "pendek",
    "cepet": "cepat",
    "ceu": "kakak perempuan",
    "cew": "cewek",
    "cewe": "cewek",
    "chuyunk": "sayang",
    "cibuk": "sibuk",
    "cimeng": "ganja",
    "cin": "cinta",
    "cipika cipiki": "cium pipi kanan cium pipi kiri",
    "ciye": "cie",
    "ciyh": "sih",
    "ckck": "ck",
    "ckepp": "cakep",
    "ckp": "cakep",
    "clbk": "cinta lama bersemi kembali",
    "cmiiw": "correct me if i'm wrong",
    "cmpr": "campur",
    "cmpur": "campur",
    "cnenk": "senang",
    "cod": "bayar ditempat",
    "cong": "banci",
    "congor": "mulut",
    "conlok": "cinta lokasi",
    "cow": "cowok",
    "cowwyy": "maaf",
    "coz": "karena",
    "cp": "siapa",
    "cpa": "siapa",
    "cpe": "capek",
    "cppe": "capek",
    "cr": "sumber",
    "cucok": "cocok",
    "cuex": "cuek",
    "cumi": "Cuma miscall",
    "cups": "culun",
    "curanmor": "pencurian kendaraan bermotor",
    "curcol": "curahan hati colongan",
    "cwek": "cewek",
    "cyin": "cinta",
    "d": "di",
    "dah": "deh",
    "dapet": "dapat",
    "de": "adik",
    "dek": "adik",
    "demen": "suka",
    "deyh": "deh",
    "dgn": "dengan",
    "diancurin": "dihancurkan",
    "dimaafin": "dimaafkan",
    "dimintak": "diminta",
    "disono": "di sana",
    "dket": "dekat",
    "dkk": "dan kawan-kawan",
    "dll": "dan lain-lain",
    "dlu": "dulu",
    "dngn": "dengan",
    "dodol": "bodoh",
    "doku": "uang",
    "dongs": "dong",
    "dpt": "dapat",
    "dri": "dari",
    "drmn": "darimana",
    "drtd": "dari tadi",
    "dst": "dan seterusnya",
    "dtg": "datang",
    "duh": "aduh",
    "duren": "durian",
    "ed": "edisi",
    "egp": "emang saya pikirin",
    "eke": "aku",
    "elu": "kamu",
    "emangnya": "memangnya",
    "emng": "memang",
    "endak": "tidak",
    "tidak": "tidak",
    "envy": "iri",
    "ex": "mantan",
    "faktakta": "fakta",
    "fax": "facsimile",
    "fifo": "first in first out",
    "folbek": "follow back",
    "fyi": "sebagai informasi",
    "gaada": "tidak ada uang",
    "gag": "tidak",
    "gaje": "tidak jelas",
    "gak papa": "tidak apa-apa",
    "gan": "juragan",
    "gantengsaya": "ganteng",
    "gaptek": "gagap teknologi",
    "gatek": "gagap teknologi",
    "gawe": "kerja",
    "gbs": "tidak bisa",
    "gebetan": "orang yang disuka",
    "geje": "tidak jelas",
    "gepeng": "gelandangan dan pengemis",
    "ghiy": "lagi",
    "gile": "gila",
    "gimana": "bagaimana",
    "gino": "gigi nongol",
    "githu": "gitu",
    "gj": "tidak jelas",
    "gmana": "bagaimana",
    "gn": "begini",
    "goblok": "bodoh",
    "gokil": "gila",
    "golput": "golongan putih",
    "gombal": "suka merayu",
    "gowes": "mengayuh sepeda",
    "gpl": "tidak pakai lama",
    "gpny": "tidak punya",
    "gpp": "tidak apa-apa",
    "gr": "gede rasa",
    "gretong": "gratis",
    "gretongan": "gratisan",
    "gt": "begitu",
    "gtau": "tidak tahu",
    "gtw": "tidak tahu",
    "gua": "saya",
    "gue": "saya",
    "guoblok": "goblok",
    "guys": "teman-teman",
    "gw": "saya",
    "gws": "cepat sembuh",
    "ha": "tertawa",
    "haghaghag": "tertawa",
    "haha": "tertawa",
    "hakhak": "tertawa",
    "hallow": "halo",
    "handak": "bahan peledak",
    "hankam": "pertahanan dan keamanan",
    "hansip": "pertahanan sipil",
    "happy": "bahagia",
    "hardcore": "keras",
    "hehe": "he",
    "hellow": "halo",
    "helo": "halo",
    "helow": "halo",
    "heters": "pembenci",
    "hey": "hai",
    "hi": "hai",
    "hlm": "halaman",
    "hlng": "hilang",
    "hny": "hanya",
    "hnya": "hanya",
    "hoax": "isu bohong",
    "houm": "rumah",
    "hr": "hari",
    "hrs": "harus",
    "hrus": "harus",
    "hubad": "hubungan angkatan darat",
    "hubdar": "perhubungan darat",
    "hubla": "perhubungan laut",
    "huff": "mengeluh",
    "huft": "mengeluh",
    "hum": "rumah",
    "humas": "hubungan masyarakat",
    "humz": "rumah",
    "idk": "saya tidak tahu",
    "ikon": "lambang",
    "ilang": "hilang",
    "ilfeel": "tidak suka",
    "ilfil": "tidak suka",
    "imba": "jago sekali",
    "imho": "in my humble opinion",
    "imoet": "imut",
    "imoetz": "imut",
    "indo": "indonesia",
    "info": "informasi",
    "isengin": "bercanda",
    "ista": "nista",
    "istaa": "nista",
    "item": "hitam",
    "itung": "hitung",
    "itungan": "hitungan",
    "iyala": "iya lah",
    "iye": "iya",
    "iyo": "iya",
    "ja": "saja",
    "jablay": "jarang dibelai",
    "jadiin": "jadi",
    "jadul": "jaman dulu",
    "jaim": "jaga image",
    "jancuk": "anjing",
    "jayus": "tidak lucu",
    "jd": "jadi",
    "jdi": "jadi",
    "jdikan": "jadikan",
    "jem": "jam",
    "jentelmen": "berani",
    "jg": "juga",
    "jga": "juga",
    "jgn": "jangan",
    "jgnkan": "jangankan",
    "jijay": "jijik",
    "jir": "anjing",
    "jkt": "jakarta",
    "jln": "jalan",
    "jnj": "janji",
    "jomblo": "tidak punya pacar",
    "jth": "jatuh",
    "jubir": "juru bicara",
    "jurdil": "jujur adil",
    "jutek": "galak",
    "jwb": "jawab",
    "k": "ke",
    "ka": "kakak",
    "kab": "kabupaten",
    "kabag": "kepala bagian",
    "kabor": "kabur",
    "kacian": "kasihan",
    "kacrut": "kacau",
    "kadit": "kepala direktorat",
    "kadiv": "kepala divisi",
    "kaga": "tidak",
    "kagak": "tidak",
    "kaka": "kakak",
    "kalo": "kalau",
    "kampret": "sialan",
    "kamtib": "keamanan dan ketertiban",
    "kamtibmas": "keamanan dan ketertiban masyarakat",
    "kamuh": "kamu",
    "kamuwh": "kamu",
    "kamyu": "kamu",
    "kanwil": "kantor wilayah",
    "kapt": "kapten",
    "karna": "karena",
    "kasat": "kepala satuan",
    "kasubbag": "kepala subbagian",
    "kasubbid": "kepala subbidang",
    "katrok": "kampungan",
    "kau": "kamu",
    "kayanya": "kayaknya",
    "kbar": "kabar",
    "kbr": "kabar",
    "kcian": "kasihan",
    "kdu": "harus",
    "keburu": "terlanjur",
    "kec": "kecamatan",
    "kedubes": "kedutaan besar",
    "kejurnas": "kejuaraan nasional",
    "kek": "seperti",
    "kekeuh": "keras kepala",
    "keknya": "kayaknya",
    "kel": "kelurahan",
    "keliatan": "kelihatan",
    "kemaren": "kemarin",
    "keneh": "masih",
    "kentot": "senggama",
    "kepengen": "mau",
    "kepikiran": "terpikirkan",
    "kepingin": "mau",
    "kepo": "mau tahu urusan orang",
    "kepsek": "kepala sekolah",
    "kere": "tidak punya uang",
    "kesbang": "kesatuan bangsa",
    "kesian": "kasihan",
    "kesra": "kesejahteraan rakyat",
    "ketauan": "ketahuan",
    "ketrima": "diterima",
    "keukeuh": "keras kepala",
    "kgiatan": "kegiatan",
    "khan": "kan",
    "kibul": "bohong",
    "kibus": "kaki busuk",
    "kimpoi": "kawin",
    "kk": "kakak",
    "kl": "kalau",
    "klian": "kalian",
    "klianz": "kalian",
    "klo": "kalau",
    "kloter": "kelompok terbang",
    "kluarga": "keluarga",
    "klw": "kalau",
    "klwrga": "keluarga",
    "km": "kamu",
    "kmari": "kemari",
    "kmps": "kampus",
    "kmpus": "kampus",
    "kmrn": "kemarin",
    "kn": "kan",
    "knal": "kenal",
    "knl": "kenal",
    "knp": "kenapa",
    "knpa": "kenapa",
    "koar": "teriak",
    "kodya": "kota madya",
    "kog": "kok",
    "komdis": "komisi disiplin",
    "kompi": "komputer",
    "komsov": "komunis sovyet",
    "komtiong": "komunis Tiongkok",
    "kongkow": "kumpul bareng teman-teman",
    "konjen": "konsulat jenderal",
    "kopdar": "kopi darat",
    "koq": "kok",
    "korup": "korupsi",
    "kpd": "kepada",
    "kpn": "kapan",
    "kptsan": "keputusan",
    "krenz": "keren",
    "krik": "garing",
    "krm": "kirim",
    "krn": "karena",
    "kt": "kita",
    "ktauan": "ketahuan",
    "ktipu": "tipu",
    "ktmu": "ketemu",
    "ktny": "katanya",
    "ktr": "kantor",
    "kudu": "harus",
    "kuper": "kurang pergaulan",
    "kuq": "kok",
    "kurng": "kurang",
    "kw": "imitasi",
    "ky": "seperti",
    "kyk": "seperti",
    "kykny": "kayanya",
    "la": "lah",
    "laka": "kecelakaan",
    "lam": "salam",
    "lambreta": "lambat",
    "lamp": "lampiran",
    "lansia": "lanjut usia",
    "lanud": "landasan udara",
    "lapas": "lembaga pemasyarakatan",
    "latgab": "latihan gabungan",
    "lbur": "libur",
    "lebay": "berlebihan",
    "leh": "boleh",
    "lekong": "laki-laki",
    "lelet": "lambat",
    "lemot": "lambat",
    "less": "kurang",
    "lg": "lagi",
    "lgi": "lagi",
    "lgkp": "lengkap",
    "lgsg": "langsung",
    "lht": "lihat",
    "liat": "lihat",
    "light": "terang",
    "linmas": "perlindungan masyarakat",
    "litbang": "penelitian dan pengembangan",
    "lmyan": "lumayan",
    "lmyn": "lumayan",
    "lngkp": "lengkap",
    "lo": "kamu",
    "loch": "loh",
    "loe": "kamu",
    "lol": "tertawa",
    "lola": "lambat berfikir",
    "lom": "belum",
    "louph": "cinta",
    "loupz": "cinta",
    "low": "kalau",
    "lowh": "kamu",
    "lp": "lupa",
    "lu": "kamu",
    "luber": "langsung, umum, bebas, dan rahasia",
    "luchu": "lucu",
    "luchuw": "lucu",
    "luff": "cinta",
    "lum": "belum",
    "luph": "cinta",
    "luthu": "lucu",
    "lw": "kamu",
    "lwn": "lawan",
    "lwt": "lewat",
    "maacih": "terima kasih",
    "maaciw": "terima kasih",
    "mabal": "bolos",
    "mabes": "markas besar",
    "macem": "macam",
    "macem-macem": "macam-macam",
    "macih": "masih",
    "madesu": "masa depan suram",
    "maem": "makan",
    "maen": "main",
    "magabut": "makan gaji buta",
    "mahatma": "maju sehat bersama",
    "maho": "homo",
    "mak": "ibu",
    "mak jang": "kaget",
    "makasih": "terima kasih",
    "maks": "maksimal",
    "maksain": "memaksa",
    "malah": "bahkan",
    "malem": "malam",
    "malu2in": "memalukan",
    "mam": "makan",
    "mamz": "makan",
    "maneh": "kamu",
    "manies": "manis",
    "maniez": "manis",
    "mantep": "mantap",
    "mao": "mau",
    "markus": "makelar kasus",
    "masi": "masih",
    "masukin": "masukkan",
    "masy": "masyarakat",
    "mba": "mbak",
    "mbual": "bual",
    "melu": "ikut",
    "mending": "lebih baik",
    "mepet": "dekat sekali",
    "mgkin": "mungkin",
    "mgkn": "mungkin",
    "mgu": "minggu",
    "mhn": "mohon",
    "migas": "minyak dan gas bumi",
    "miker": "minuman keras",
    "mikol": "minuman beralkohol",
    "milis": "mailing list",
    "miras": "minuman keras",
    "mksd": "maksud",
    "mlah": "malah",
    "mls": "malas",
    "mngkn": "mungkin",
    "mnolak": "tolak",
    "mnt": "minta",
    "mo": "mau",
    "moge": "motor gede",
    "mokad": "mati",
    "mokat": "mati",
    "moso": "masa",
    "mosok": "masa",
    "most": "paling",
    "mpe": "sampai",
    "msh": "masih",
    "msk": "masuk",
    "mskpn": "meskipun",
    "mslh": "masalah",
    "msng2": "masing-masing",
    "mt": "makan teman",
    "muahal": "mahal",
    "mubes": "musyawarah besar",
    "muker": "musyawarah kerja",
    "mulu": "melulu",
    "mumet": "pusing",
    "mumpung": "selagi",
    "muna": "munafik",
    "munas": "musyawarah nasional",
    "munaslub": "musyawarah nasional luar biasa",
    "munfik": "munafik",
    "muntaber": "muntah dan berak",
    "musda": "musyawarah daerah",
    "musti": "mesti",
    "muup": "maaf",
    "muupz": "maaf",
    "muuv": "maaf",
    "mw": "now watching",
    "mz": "mas",
    "n": "dan",
    "nal": "kenal",
    "nanam": "menanam",
    "nangis": "menangis",
    "nanya": "bertanya",
    "naon": "apa",
    "napa": "kenapa",
    "napi": "narapidana",
    "napol": "narapidana politik",
    "napza": "narkotika, alkohol, psikotropika, dan zat adiktif ",
    "naq": "anak",
    "narkoba": "narkotika, psikotropika, dan obat terlarang",
    "narsis": "bangga pada diri sendiri",
    "nasgor": "nasi goreng",
    "nax": "anak",
    "nda": "tidak",
    "ndak": "tidak",
    "ndiri": "sendiri",
    "ndut": "gendut",
    "ne": "ini",
    "nekolim": "neokolonialisme",
    "nekolin": "neokolonialisme",
    "nelfon": "menelepon",
    "nembak": "menyatakan cinta",
    "next": "lanjut",
    "ngabis2in": "menghabiskan",
    "ngabuburit": "menunggu berbuka puasa",
    "ngakak": "tertawa",
    "ngaku": "mengaku",
    "ngambek": "marah",
    "ngambil": "mengambil",
    "ngampus": "pergi ke kampus",
    "nganggur": "tidak punya pekerjaan",
    "ngantri": "mengantri",
    "ngapah": "kenapa",
    "ngapain": "sedang apa",
    "ngaret": "terlambat",
    "ngaruh": "berpengaruh",
    "ngasih": "memberikan",
    "ngawur": "berbicara sembarangan",
    "ngebandel": "berbuat bandel",
    "ngebully": "intimidasi",
    "ngeceng": "kumpul bareng-bareng",
    "ngegosip": "bergosip",
    "ngeh": "sadar",
    "ngehe": "kesal",
    "ngeklaim": "mengklaim",
    "ngekos": "tinggal di kos",
    "ngeksis": "menjadi eksis",
    "ngelamar": "melamar",
    "ngeles": "berkilah",
    "ngeliat": "melihat",
    "ngelidur": "menggigau",
    "ngemeng": "bicara terus-terusan",
    "ngentotin": "senggama",
    "ngerampok": "merampok",
    "ngerti": "mengerti",
    "ngga": "tidak",
    "nggak": "tidak",
    "ngibul": "berbohong",
    "ngikut": "ikut",
    "ngiler": "mau",
    "nginep": "menginap",
    "ngiri": "iri",
    "ngisi": "mengisi",
    "ngisiin": "mengisikan",
    "ngmg": "bicara",
    "ngmng": "bicara",
    "ngocol": "lucu",
    "ngomong": "bicara",
    "ngomongin": "membicarakan",
    "ngubek2": "mencari-cari",
    "ngumpet": "sembunyi",
    "ngumpul": "berkumpul",
    "ngurus": "mengurus",
    "ni": "ini",
    "nie": "ini",
    "nih": "ini",
    "nipu": "tipu",
    "niyh": "nih",
    "nmenarik": "menarik",
    "nmr": "nomor",
    "nntn": "nonton",
    "nobar": "nonton bareng",
    "np": "now playing",
    "ntar": "nanti",
    "ntn": "nonton",
    "numpuk": "bertumpuk",
    "nutupin": "menutupi",
    "nyari": "mencari",
    "nyariin": "mencari",
    "nyasar": "tersesat",
    "nyekar": "menyekar",
    "nyela": "cela",
    "nyembah": "sembah",
    "nyerang": "serang",
    "nyiapin": "mempersiapkan",
    "nyicil": "mencicil",
    "nyiram": "menyiram",
    "nyoblos": "mencoblos",
    "nyok": "ayo",
    "nyokap": "ibu",
    "o/": "oleh",
    "ogah": "tidak mau",
    "ok": "ok",
    "ol": "online",
    "ongkir": "ongkos kirim",
    "oot": "out of topic",
    "org2": "orang-orang",
    "ortu": "orang tua",
    "otda": "otonomi daerah",
    "otw": "sedang di jalan",
    "pacal": "pacar",
    "pake": "pakai",
    "pala": "kepala",
    "pansus": "panitia khusus",
    "paranoid": "takut",
    "parpol": "partai politik",
    "parte": "partai",
    "pasutri": "pasangan suami istri",
    "pd": "pada",
    "pede": "percaya diri",
    "pelatnas": "pemusatan latihan nasional",
    "pemda": "pemerintah daerah",
    "pemkot": "pemerintah kota",
    "pemred": "pemimpin redaksi",
    "penertiban": "tertib",
    "penjas": "pendidikan jasmani",
    "perda": "peraturan daerah",
    "perhatiin": "perhatikan",
    "pesenan": "pesanan",
    "pgang": "pegang",
    "pi": "tapi",
    "pilkada": "pemilihan kepala daerah",
    "pisan": "sangat",
    "pk": "penjahat kelamin",
    "plg": "paling",
    "plis": "tolong",
    "plisss": "tolong",
    "pls": "tolong",
    "pmrnth": "pemerintah",
    "pndukung": "pendukung",
    "polantas": "polisi lalu lintas",
    "ponpes": "pondok pesantren",
    "pp": "pulang pergi",
    "prg": "pergi",
    "priksa": "periksa",
    "prnh": "pernah",
    "pro": "profesional",
    "problem": "masalah",
    "psen": "pesan",
    "psn": "pesan",
    "pst": "pasti",
    "psti": "pasti",
    "pswt": "pesawat",
    "puanas": "panas",
    "pw": "posisi nyaman",
    "qmo": "kamu",
    "qmu": "kamu",
    "qt": "kita",
    "rakor": "rapat koordinasi",
    "rame": "ramai",
    "ranmor": "kendaraan bermotor",
    "raskin": "rakyat miskin",
    "re": "reply",
    "red": "redaksi",
    "ref": "referensi",
    "reg": "register",
    "rehab": "rehabilitasi",
    "rejeki": "rezeki",
    "reklamuk": "reklamasi",
    "rempong": "sulit",
    "renstra": "rencana strategis",
    "repp": "balas",
    "reskrim": "reserse kriminal",
    "restik": "reserse narkotika",
    "rhs": "rahasia",
    "rights": "benar",
    "rmh": "rumah",
    "ru": "baru",
    "rubahnn": "rubah",
    "ruko": "rumah toko",
    "rusunawa": "rumah susun sewa",
    "ruz": "terus",
    "rv": "redvelvet",
    "sadaar": "sadar",
    "saia": "saya",
    "salting": "salah tingkah",
    "sampe": "sampai",
    "samsek": "sama sekali",
    "sapose": "siapa",
    "satpam": "satuan pengamanan",
    "sbb": "sebagai berikut",
    "sbh": "sebuah",
    "sbnrny": "sebenarnya",
    "scr": "secara",
    "sdgkn": "sedangkan",
    "sdkt": "sedikit",
    "se7": "setuju",
    "sebelas dua belas": "mirip",
    "sembako": "sembilan bahan pokok",
    "sempet": "sempat",
    "sendratari": "seni drama tari",
    "sept": "september",
    "seting": "akting",
    "setting": "atur",
    "sgt": "sangat",
    "shg": "sehingga",
    "siech": "sih",
    "sikon": "situasi dan kondisi",
    "simiskin": "miskin",
    "sinetron": "sinema elektronik",
    "siramin": "siramkan",
    "sj": "saja",
    "skalian": "sekalian",
    "sklh": "sekolah",
    "skt": "sakit",
    "slesai": "selesai",
    "sll": "selalu",
    "slma": "selama",
    "slsai": "selesai",
    "sma": "sama",
    "smpt": "sempat",
    "smw": "semua",
    "sndiri": "sendiri",
    "sni": "sini",
    "sohib": "teman",
    "soljum": "sholat jumat",
    "solve": "solusi",
    "somse": "sombong sekali",
    "songong": "sombong",
    "sorry": "maaf",
    "sory": "maaf",
    "sosbud": "sosial-budaya",
    "sosek": "sosial-ekonomi",
    "sospol": "sosial-politik",
    "sotoy": "sok tahu",
    "sowry": "maaf",
    "spa": "siapa",
    "spd": "sepeda",
    "sppa": "siapa",
    "sprti": "seperti",
    "spt": "seperti",
    "spy": "supaya",
    "srtfkt": "sertifikat",
    "stelah": "setelah",
    "stiap": "setiap",
    "still": "masih",
    "stlh": "setelah",
    "subbag": "subbagian",
    "suk": "masuk",
    "sumbangin": "sumbangkan",
    "sumpek": "sempit",
    "sy": "saya",
    "syg": "sayang",
    "syp": "siapa",
    "t4": "tempat",
    "tabanas": "tabungan pembangunan nasional",
    "tahi": "kotoran",
    "taik": "tahi",
    "tajir": "kaya",
    "tak": "tidak",
    "tar": "nanti",
    "tau": "tahu",
    "tauk": "tahu",
    "taun": "tahun",
    "taw": "tahu",
    "tawh": "tahu",
    "td": "tadi",
    "tdi": "tadi",
    "tdk": "tidak",
    "te2p": "tetap",
    "teh": "kakak perempuan",
    "tekor": "rugi",
    "telat": "terlambat",
    "telkom": "telekomunikasi",
    "telmi": "telat berpikir",
    "telp": "telepon",
    "temen": "teman",
    "temen2": "teman-teman",
    "tengil": "menyebalkan",
    "tengok": "menjenguk",
    "tepar": "terkapar",
    "terbitin": "terbitkan",
    "tggu": "tunggu",
    "tgl": "tanggal",
    "tgu": "tunggu",
    "thanks": "terima kasih",
    "thankz": "terima kasih",
    "thd": "terhadap",
    "thn": "tahun",
    "thx": "terima kasih",
    "tilang": "bukti pelanggaran",
    "tilep": "tilap",
    "tioghoa": "tionghoa",
    "tipi": "TV",
    "tipiwan": "TvOne",
    "tirani": "tiran",
    "tkg": "tukang",
    "tks": "terima kasih",
    "tll": "terlalu",
    "tlp": "telepon",
    "tlpn": "telepon",
    "tls": "tulis",
    "tman": "teman",
    "tmbah": "tambah",
    "tmbh": "tambah",
    "tmen2": "teman-teman",
    "tmn2": "teman-teman",
    "tmpah": "tumpah",
    "tmph": "tumpah",
    "tmpt": "tempat",
    "tnda": "tanda",
    "tngu": "tunggu",
    "tnh": "tanah",
    "tnyta": "ternyata",
    "togel": "toto gelap",
    "tokai": "tai",
    "toserba": "toko serba ada",
    "tp": "tapi",
    "tpi": "tapi",
    "tq": "terima kasih",
    "trdhulu": "terdahulu",
    "tren": "trend",
    "trending": "trend",
    "trgntg": "tergantung",
    "trima": "terima kasih",
    "trims": "terima kasih",
    "trlalu": "terlalu",
    "trm": "terima",
    "trs": "terus",
    "trutama": "terutama",
    "ts": "penulis",
    "tsangka": "tersangka",
    "tst": "tahu sama tahu",
    "ttg": "tentang",
    "tuch": "tuh",
    "tuir": "tua",
    "tw": "tahu",
    "u": "kamu",
    "uasai": "kuasa",
    "ud": "sudah",
    "udah": "sudah",
    "ujg": "ujung",
    "ul": "ulangan",
    "unyu": "lucu",
    "uplot": "unggah",
    "urang": "saya",
    "usah": "perlu",
    "utk": "untuk",
    "valas": "valuta asing",
    "w/": "dengan",
    "wadir": "wakil direktur",
    "wamil": "wajib militer",
    "warkop": "warung kopi",
    "warteg": "warung tegal",
    "waspadalah": "waspada",
    "wat": "buat",
    "watuk": "batuk",
    "wkt": "waktu",
    "wkwkkw": "tertawa",
    "wtb": "beli",
    "wtf": "what the fuck",
    "wts": "jual",
    "wtt": "tukar",
    "xixixi": "tertawa",
    "y": "ya",
    "ya": "iya",
    "yap": "iya",
    "yaudah": "ya sudah",
    "yawdah": "ya sudah",
    "yg": "yang",
    "yl": "yang lain",
    "yo": "iya",
    "yowes": "ya sudah",
    "yup": "iya",
    "zonk": "bodoh",
}

slang_in_df = {
    "udeh": "sudah",
    "sngat": "sangat",
    "hdeh": "haduh",
    "huuuuh": "mengeluh",
    "admint": "admin",
    "maren": "kemarin",
    "mendftrkn": "mendaftarkan",
    "nurun": "menurun",
    "smakin": "semakin",
    "pngduan": "pengaduan",
    "hh": "haha",
    "vctapi": "video call tapi",
    "gimanasi": "bagaimana sih",
    "pernahh": "pernah",
    "katro": "kampungan",
    "whatsap": "whatsapp",
    "fahami": "pahami",
    "manpat": "manfaat",
    "dibales": "dibalas",
    "apalikasi": "aplikasi",
    "aplikasii": "aplikasi",
    "palikasi": "aplikasi",
    "aplikas": "aplikasi",
    "aplikadi": "aplikasi",
    "aplisai": "aplikasi",
    "aplksinya": "aplikasinya",
    "beuu": "aduh",
    "cheos": "kacau",
    "layanannnya": "layanannya",
    "dibidang": "di bidang",
    "smga": "semoga",
    "tapipak": "tapi pak",
    "skrinsyut": "tangkapan layar",
    "screnshot": "tangkapan layar",
    "secrenshot": "tangkapan layar",
    "screenshot": "tangkapan layar",
    "shoot": "tangkapan layar",
    "shot": "tangkapan layar",
    "mbgking": "m-banking",
    "mbking": "m-banking",
    "mbankinh": "m-banking",
    "mbanking": "m-banking",
    "mbankingnya": "m-bankingnya",
    "bankingnyaa": "bankingnya",
    "gopaydana": "gopay dana",
    "antri": "antre",
    "perbaharu": "perbarui",
    "diprbarui": "diperbarui",
    "popush": "pop up",
    "poppus": "pop up",
    "dibayarin": "dibayarkan",
    "bangusss": "bagus",
    "bggtttt": "sangat",
    "bgttapi": "sangat tapi",
    "bget": "sangat",
    "bertele": "bertele-tele",
    "bayr": "bayar",
    "mohaon": "mohon",
    "abissss": "habis",
    "negri": "negeri",
    "bgai": "bagai",
    "dllterimakasih": "dll terima kasih",
    "kalijujur": "kali jujur",
    "malahh": "malah",
    "ng": "tidak",
    "tah": "entah",
    "uat": "buat",
    "ngestak": "macet",
    "gambr": "gambar",
    "prangkat": "perangkat",
    "teransaksi": "transaksi",
    "traansaksi": "transaksi",
    "trx": "transaksi",
    "ngelag": "macet",
    "niudh": "ini sudah",
    "amd": "alhamdulillah",
    "bukamhon": "buka mohon",
    "gagaluda": "gagal sudah",
    "ngajukan": "mengajukan",
    "mandiiri": "mandiri",
    "sajatrimakasih": "saja terima kasih",
    "susahy": "susahnya",
    "rekeningn": "rekeningnya",
    "perbaki": "perbaiki",
    "rekomendes": "rekomendasi",
    "digunainn": "digunakan",
    "krngkao": "kurang kalau",
    "nemuin": "menemukan",
    "naikin": "menaikkan",
    "asv": "aplikasi",
    "aturanya": "aturannya",
    "ngeluarin": "mengeluarkan",
    "inet": "internet",
    "diaurih": "disuruh",
    "infonya": "informasinya",
    "drpd": "daripada",
    "dikasih": "diberi",
    "pasn": "pesan",
    "trakhir": "terakhir",
    "cacaaaatt": "cacat",
    "bae": "baik",
    "orng": "orang",
    "inikarna": "ini karena",
    "sndri": "sendiri",
    "nyatidak": "nya tidak",
    "ilangin": "hilangkan",
    "oermintaan": "permintaan",
    "cdgn": "cadangan",
    "yangg": "yang",
    "veeifikasi": "verifikasi",
    "veripikasi": "verifikasi",
    "vrifikasiku": "verifikasiku",
    "pirivikasi": "verifikasi",
    "veriffikasi": "verifikasi",
    "verivicasi": "verifikasi",
    "verivikasikalo": "verifikasi kalau",
    "verivikasinya": "verifikasinya",
    "assalamualaikumknp": "assalamualaikum kenapa",
    "komplenan": "komplainan",
    "dolot": "lambat",
    "adala": "adalah",
    "nyah": "nya",
    "ginimohon": "begini mohon",
    "keanapa": "kenapa",
    "kenapaaa": "kenapa",
    "capta": "captcha",
    "kamren": "kemarin",
    "fav": "favorit",
    "bertranksasi": "bertransaksi",
    "selvi": "swafoto",
    "berselfi": "berswafoto",
    "trasnfer": "transfer",
    "mentrasnfer": "mentransfer",
    "nyobak": "mencoba",
    "mnggunakan": "menggunakan",
    "menggunkana": "menggunakan",
    "pinyuh": "penuh",
    "pnjaman": "pinjaman",
    "rawas": "rawan",
    "niihh": "ini",
    "sigiri": "segera",
    "copas": "salin tempel",
    "mulumataku": "melulu mataku",
    "swlalu": "selalu",
    "selelu": "selalu",
    "beratin": "memberatkan",
    "trimakne": "terima kasih",
    "trlbih": "terlebih",
    "swbwlumnya": "sebelumnya",
    "padalah": "padahal",
    "kuh": "ku",
    "du": "aduh",
    "sistrm": "sistem",
    "sistemu": "sistemmu",
    "mrasa": "merasa",
    "mon": "min",
    "bsihri": "bsi hari",
    "bgaimna": "bagaimana",
    "orda": "order",
    "aneg": "aneh",
    "kmana": "kemana",
    "minggi": "minggu",
    "banyakterimakasih": "banyak terima kasih",
    "pket": "paket",
    "lemog": "lambat",
    "poto": "foto",
    "ntah": "entah",
    "nyelesain": "menyelesaikan",
    "bjsa": "bisa",
    "aktivas": "aktivasi",
    "telvon": "telepon",
    "nentu": "menentu",
    "nich": "nih",
    "cm": "cuma",
    "anyingngaktipkn": "anjing mengaktifkan",
    "walamdulillaah": "alhamdulillah",
    "egak": "tidak",
    "okno": "ok num",
    "andoid": "android",
    "mnutup": "menutup",
    "bobile": "mobile",
    "mobili": "mobile",
    "sabisa": "sebisa",
    "brkurang": "berkurang",
    "pidcol": "video call",
    "videcall": "video call",
    "sgat": "sangat",
    "ngembangin": "mengembangkan",
    "nyadar": "sadar",
    "gantii": "ganti",
    "dupdate": "diupdate",
    "abdate": "update",
    "upadate": "update",
    "upgread": "upgrade",
    "upgred": "upgrade",
    "kekuar": "keluar",
    "elin": "eling",
    "sanganat": "sangat",
    "rekning": "rekening",
    "nyelek": "jelek",
    "ngutang": "berhutang",
    "ayoklah": "ayo lah",
    "bantuanya": "bantuannya",
    "tersibet": "teribet",
    "pelaynan": "pelayanan",
    "unruk": "untuk",
    "tl": "telepon",
    "abk": "anak buah kapal",
    "puntang": "pontang",
    "aat": "saat",
    "lgbbrapa": "lagi beberapa",
    "banyaksdh": "banyak sudah",
    "jgak": "juga",
    "setalah": "setelah",
    "setlah": "setelah",
    "gakbs": "tidak bisa",
    "gabsa": "tidak bisa",
    "gabisaa": "tidak bisa",
    "dehhh": "deh",
    "dahh": "deh",
    "selesain": "selesaikan",
    "ngeseliiin": "mengkesalkan",
    "buanget": "sangat",
    "tereak": "teriak",
    "amrik": "amerika",
    "samaung": "samsung",
    "costumer": "customer",
    "custemer": "customer",
    "custemertolong": "customer tolong",
    "custumer": "customer",
    "cust": "customer",
    "tuker": "tukar",
    "paok": "bodoh",
    "seneng": "senang",
    "meninggakan": "meninggalkan",
    "readmi": "redmi",
    "rdmi": "redmi",
    "keteler": "ke teller",
    "sspas": "pas",
    "dftr": "daftar",
    "daptr": "daftar",
    "gacor": "bagus",
    "bangkin": "banking",
    "musinginsaran": "memusingkan saran",
    "tfnya": "transfernya",
    "apdat": "update",
    "dperbaiki": "diperbaiki",
    "tulisany": "tulisannya",
    "waaa": "wah",
    "dalan": "dalam",
    "sabgat": "sangat",
    "mbanget": "banget",
    "wih": "wah",
    "barkot": "barcode",
    "ingris": "inggris",
    "gl": "gagal",
    "bermalah": "bermasalah",
    "aslm": "assalamualaikum",
    "marakké": "maraknya",
    "dmnuntung": "dimana untung",
    "denger": "dengar",
    "apasi": "apa sih",
    "kentank": "kentang",
    "mentog": "mentok",
    "aplujungnya": "aplikasi ujungnya",
    "jelekin": "menjelekkan",
    "prindapan": "prindavan",
    "indosia": "indonesia",
    "cepran": "cepatan",
    "ktpotppin": "ktp otp pin",
    "ngerapel": "merapel",
    "trobel": "masalah",
    "maslahy": "masalahnya",
    "brsn": "barusan",
    "seblm": "sebelum",
    "responsdh": "respon sudah",
    "dimpen": "disimpan",
    "mendesk": "mendesak",
    "waahh": "wah",
    "heddeh": "haduh",
    "bgm": "bagaimana",
    "biyond": "beyond",
    "bungul": "bodoh",
    "taiiiiii": "tai",
    "taiii": "tai",
    "taikkk": "tai",
    "shittt": "sial",
    "poop": "kotoran",
    "njirrr": "anjir",
    "prngembalianya": "pengembaliannya",
    "levih": "lebih",
    "ttp": "tetap",
    "ngblang": "kosong",
    "lahkerja": "lah kerja",
    "terimakaaih": "terima kasih",
    "trimakasih": "terima kasih",
    "cab": "cabang",
    "esmosi": "emosi",
    "emosii": "emosi",
    "ndg": "undang",
    "adek": "adik",
    "plosok": "pelosok",
    "tsb": "tersebut",
    "aktifkn": "aktifkan",
    "dusini": "di sini",
    "cumaa": "cuma",
    "trsniat": "terus niat",
    "kerna": "karena",
    "mkir": "mikir",
    "juman": "cuma",
    "memintak": "meminta",
    "msuk": "masuk",
    "terah": "terserah",
    "kezel": "kesal",
    "kemudiam": "kemudian",
    "delai": "jeda",
    "brapa": "berapa",
    "gagalklo": "gagal kalau",
    "erorklu": "eror kalau",
    "hijauklo": "hijau kalau",
    "bankkalo": "bank kalau",
    "klaw": "kalau",
    "dnk": "dong",
    "gni": "begini",
    "ngeti": "mengerti",
    "sat": "satu",
    "dsbnya": "dan sebagainya",
    "dateskrg": "date sekarang",
    "smpai": "sampai",
    "ahir": "akhir",
    "iniapalagi": "ini apalagi",
    "habispadahal": "habis padahal",
    "bangettgampang": "sangat gampang",
    "perubahansangat": "perubahan sangat",
    "malamtlg": "malam tolong",
    "transaksigak": "transaksi tidak",
    "nihhrs": "nih harus",
    "terbarulah": "terbaru lah",
    "enaknyatolong": "enaknya tolong",
    "lambatbagai": "lambat bagai",
    "susahtransfer": "susah transfer",
    "facesangat": "face sangat",
    "ribetsaya": "ribet saya",
    "mobilebharus": "mobile harus",
    "oplashadeeuhhh": "oplas haduh",
    "komplainawalnya": "komplain awalnya",
    "kecewaudh": "kecewa sudah",
    "mobilenyakesel": "mobilenya kesal",
    "nasabahcall": "nasabah call",
    "pulsatop": "pulsa top",
    "susahmaleh": "susah malah",
    "wajahaplikasi": "wajah aplikasi",
    "aprilhari": "april hari",
    "sayapadahal": "saya padahal",
    "bapakibu": "bapak ibu",
    "kebacakalau": "kebaca kalau",
    "bukanmalah": "bukan malah",
    "daruratt": "darurat",
    "lagibahkan": "lagi bahkan",
    "sekalijadi": "sekali jadi",
    "apkciptakan": "aplikasi ciptakan",
    "keseharianaman": "keseharian aman",
    "solusinyasaya": "solusinya saya",
    "menarikmudah": "menarik mudah",
    "transaksidebes": "transaksi terbaik",
    "lengkapgampang": "lengkap gampang",
    "lemotgood": "lambat good",
    "ribetpaham": "ribet paham",
    "punyasllu": "punya selalu",
    "apapunsllu": "apapun selalu",
    "amangampang": "aman gampang",
    "utamamakin": "utama makin",
    "lainbikin": "lain bikin",
    "gangguanmasak": "gangguan masa",
    "bsiuntuk": "bsi untuk",
    "brilinkapes": "brilink apes",
    "matiidupin": "mati hidupkan",
    "erornutup": "eror menutup",
    "bermasalahsmua": "bermasalah semua",
    "lagiwaktu": "lagi waktu",
    "ribusaldo": "ribu saldo",
    "kerenpraktissimpledan": "keren praktis simpel dan",
    "tindakanyang": "tindakan yang",
    "ujungujungnya": "ujung ujungnya",
    "sendirijadi": "sendiri jadi",
    "otomatiskecewa": "otomatis kecewa",
    "jelasngabisin": "jelas menghabiskan",
    "sendiritiba": "sendiri tiba",
    "cepatterima": "cepat terima",
    "terusakhirnya": "terus akhirnya",
    "besarbaru": "besar baru",
    "terussssss": "terus",
    "transaksitop": "transaksi top",
    "buang²": "buang buang",
    "bantingaktivasi": "banting aktivasi",
    "lemotkeluar": "lambat keluar",
    "mudahbnyk": "mudah banyak",
    "keluaseringrrkecewa": "keluar sering kecewa",
    "bangettolong": "banget tolong",
    "guysdh": "guys sudah",
    "buatambiluang": "buat ambil uang",
    "ribetgood": "ribet good",
    "kerensih": "keren sih",
    "ampinvideo": "ampun video",
    "dibukajadi": "dibuka jadi",
    "sendirisetiap": "sendiri setiap",
    "amankeren": "aman keren",
    "lengkapaplikasi": "lengkap aplikasi",
    "alhamdullilahlayanan": "alhamdulillah layanan",
    "aplikainyamksh": "aplikasinya terima kasih",
    "lainterus": "lain terus",
    "dipakaimobile": "dipakai mobile",
    "sekarangsudah": "sekarang sudah",
    "amanbsi": "aman bsi",
    "mengoperasikanyasangat": "mengoperasikannya sangat",
    "callgiliran": "call giliran",
    "byongiliran": "byond giliran",
    "sekaliburuan": "sekali buruan",
    "cepatsegera": "cepat segera",
    "keblokircari": "keblokir cari",
    "salahlalu": "salah lalu",
    "infomaret": "info maret",
    "awalawal": "awal awal",
    "ribetmau": "ribet mau",
    "pagisiangsore": "pagi siang sore",
    "payahverifikasi": "payah verifikasi",
    "kedanagimana": "ke dana bagaimana",
    "payahguoblook": "payah goblok",
    "masuknyaemosi": "masuknya emosi",
    "aplikasinyadibilang": "aplikasinya dibilang",
    "masukparahhhhh": "masuk parah",
    "sekaliberkali": "sekali berkali",
    "parahsetelah": "parah setelah",
    "benartetap": "benar tetap",
    "hadehmau": "haduh mau",
    "hpbahkan": "hp bahkan",
    "leletnasabah": "lambat nasabah",
    "bukanhanya": "bukan hanya",
    "transaksitepatcepat": "transaksi tepat cepat",
    "mendowloadnyasetiap": "mendownloadnya setiap",
    "repotrepot": "repot repot",
    "memudahkantrm": "memudahkan terima",
    "transferudah": "transfer sudah",
    "masyallahsemoga": "masyaallah semoga",
    "lamapaketiba": "lama pakai tiba",
    "terdekataplikasi": "terdekat aplikasi",
    "dibukamana": "dibuka mana",
    "bisaalasan": "bisa alasan",
    "bagusbagusbagus": "bagus bagus bagus",
    "nasabahsmoga": "nasabah semoga",
    "terusmana": "terus mana",
    "memuaskansebab": "memuaskan sebab",
    "iniuntuk": "ini untuk",
    "membantupokoknya": "membantu pokoknya",
    "nihpelayanan": "nih pelayanan",
    "mulutolong": "melulu tolong",
    "praktisbuat": "praktis buat",
    "aplikasinyasolusi": "aplikasinya solusi",
    "mobiletopup": "mobile top up",
    "adminaktivasi": "admin aktivasi",
    "responsalangkah": "respon alangkah",
    "gambarscreenshot": "gambar screenshot",
    "sayatolong": "saya tolong",
    "burukuntuk": "buruk untuk",
    "mudahhemat": "mudah hemat",
    "sayacuma": "saya cuma",
    "inivsangart": "ini sangat",
    "nyaadilihat": "nya dilihat",
    "minmental": "admin mental",
    "tidaksungguh": "tidak sungguh",
    "sistemnyasemangat": "sistemnya semangat",
    "bulanpengaduan": "bulan pengaduan",
    "gagaldan": "gagal dan",
    "aplikasinyajd": "aplikasinya jadi",
    "inianda": "ini anda",
    "nihpadahal": "nih padahal",
    "jutekyang": "jutek yang",
    "masuknyalupa": "masuknya lupa",
    "erorlelet": "eror lambat",
    "hallosaya": "halo saya",
    "sendirig": "sendiri tidak",
    "mantapks": "mantap",
    "aplikasipadahal": "aplikasi padahal",
    "bingungini": "bingung ini",
    "byonndtf": "byond transfer",
    "lagijangan": "lagi jangan",
    "burukmau": "buruk mau",
    "uangmakasih": "uang terima kasih",
    "masukharus": "masuk harus",
    "bukasering": "buka sering",
    "jutanke": "jutaan ke",
    "payahhparahh": "payah parah",
    "updatepdhal": "update padahal",
    "baguscabang": "bagus cabang",
    "benartolong": "benar tolong",
    "buatsdh": "buat sudah",
    "bagusmemudahkan": "bagus memudahkan",
    "sykalau": "saya kalau",
    "bingungpake": "bingung pakai",
    "mantabproses": "mantap proses",
    "errorselalu": "error selalu",
    "assalamualaikumaplikasinya": "assalamualaikum aplikasinya",
    "gangguanketika": "gangguan ketika",
    "inicoba": "ini coba",
    "pinfingerprint": "pin fingerprint",
    "kedepanyaaa": "kedepannya",
    "bagussimple": "bagus simpel",
    "jalanmantap": "jalan mantap",
    "aktivasinyaribet": "aktivasinya ribet",
    "semuaga": "semua tidak",
    "ngecek²": "mengecek",
    "pembayaran²": "pembayaran",
    "susah²": "susah",
    "hari²": "hari hari",
    "update²": "update",
    "sebentar²": "sebentar",
    "menu²nya": "menu menunya",
    "blok²": "blok",
    "awal²": "awal awal",
    "berulang²": "berulang ulang",
    "embel²": "embel embel",
    "repott²": "repot",
    "pusat²": "pusat",
    "cape²": "capek",
    "banting²": "banting",
    "nyuruh²": "menyuruh",
    "apa²in": "apa apaan",
    "gagalgara²": "gagal gara gara",
    "kecewaaaa": "kecewa",
    "parahhhhh": "parah",
    "parahhhhhh": "parah",
    "bukaaa": "buka",
    "mobileee": "mobile",
    "ampuuun": "ampun",
    "ampiuuuun": "ampun",
    "ampuunn": "ampun",
    "hahahahahahahahhahaha": "haha",
    "wkwkww": "tertawa",
    "wkwwkk": "tertawa",
    "kereennn": "keren",
    "tolooooollll": "bodoh",
    "niiii": "nih",
    "ituuu": "itu",
    "pleasee": "please",
    "𝒅𝒊𝒃𝒑𝒂𝒌𝒆": "dipakai",
    "𝒎𝒂𝒏𝒕𝒂𝒑𝒑": "mantap",
    "𝒊𝒏𝒊": "ini",
    "klok": "kalau",
    "sakali": "sekali",
    "nungguin": "menunggu",
    "hadeehhh": "haduh",
    "cobak": "coba",
    "ingn": "ingin",
    "pelangganya": "pelanggannya",
    "rekng": "rekening",
    "sudaj": "sudah",
    "banya": "banyak",
    "gblok": "goblok",
    "bwat": "buat",
    "bberapa": "beberapa",
    "kenyaman": "kenyamanan",
    "piye": "bagaimana",
    "lodingny": "loadingnya",
    "habisin": "menghabiskan",
    "ngedip": "berkedip",
    "jngn": "jangan",
    "hapal": "hafal",
    "accoun": "akun",
    "orofesional": "profesional",
    "ikutan": "ikut",
    "sikek": "susah",
    "terdftar": "terdaftar",
    "pringatan": "peringatan",
    "penggupgradean": "pengupgradean",
    "tukusannya": "tulisannya",
    "digitu": "digit",
    "hduh": "haduh",
    "semejak": "semenjak",
    "betulkan": "membetulkan",
    "lncarrr": "lancar",
    "jumaat": "jumat",
    "keutungan": "keuntungan",
    "usngnya": "uangnya",
    "wihh": "wah",
    "kya": "seperti",
    "keditek": "terdeteksi",
    "mobiel": "mobile",
    "baguss": "bagus",
    "ngirim": "mengirim",
    "bikinlah": "buatlah",
    "bantuin": "bantu",
    "pembayaraanya": "pembayarannya",
    "diperbaharui": "diperbarui",
    "renov": "renovasi",
    "centre": "center",
    "alhdllh": "alhamdulillah",
    "kembangin": "kembangkan",
    "persulit": "mempersulit",
    "direspon": "direspons",
    "sumpa": "sumpah",
    "disa": "bisa",
    "garcep": "gerak cepat",
    "superr": "super",
    "bayon": "byond",
    "menyebal": "menyebalkan",
    "teansfer": "transfer",
    "benerr": "benar",
    "perbaharuan": "pembaruan",
    "keluhkan": "mengeluhkan",
    "langaung": "langsung",
    "rebeeett": "ribet",
    "plng": "paling",
    "kjadiannya": "kejadiannya",
    "nyusain": "menyusahkan",
    "bagaiman": "bagaimana",
    "dipersusah": "dipersulit",
    "ecomerse": "e-commerce",
    "pey": "pay",
    "ngg": "tidak",
    "toll": "bodoh",
    "knapa": "kenapa",
    "sihz": "sih",
    "kyg": "kayak",
    "gegara": "gara-gara",
    "kdih": "kasih",
    "kepenuhan": "penuh",
    "amplikasinya": "aplikasinya",
    "mbeking": "m-banking",
    "ngubungi": "menghubungi",
    "jugaak": "juga",
    "goo": "bagus",
    "terbelokir": "terblokir",
    "dzalim": "zalim",
    "itny": "itunya",
    "rokomended": "rekomendasi",
    "tempt": "tempat",
    "mbaking": "m-banking",
    "waa": "wah",
    "nyangkutnya": "tersangkutnya",
    "prubahan": "perubahan",
    "adalan": "adalah",
    "pelyanan": "pelayanan",
    "keamananya": "keamanannya",
    "sik": "sih",
    "alhamdunillah": "alhamdulillah",
    "malesin": "malas",
    "tulosan": "tulisan",
    "berenti": "berhenti",
    "bacotnya": "banyak bicaranya",
    "ngapdet": "update",
    "dihubungin": "dihubungi",
    "admi": "admin",
    "sdkit": "sedikit",
    "dlamm": "dalam",
    "tfudh": "transfer sudah",
    "lebiih": "lebih",
    "qriss": "qris",
    "ubgrade": "upgrade",
    "pertambah": "bertambah",
    "jelekkk": "jelek",
    "dtungguin": "ditungguin",
    "mnbaking": "m-banking",
    "pertma": "pertama",
    "jelekmales": "jelek malas",
    "ngetiknya": "mengetiknya",
    "gak": "tidak",
    "antrian": "antrean",
    "segela": "segala",
    "bbrp": "beberapa",
    "mantaf": "mantap",
    "omment": "komen",
    "degdeg": "deg-degan",
    "bugus": "bagus",
    "membut": "membuat",
    "paan": "apaan",
    "lalot": "lambat",
    "bertansaksinya": "bertransaksinya",
    "dateng": "datang",
    "kebangetan": "keterlaluan",
    "males": "malas",
    "smn": "semenjak",
    "dikonfirm": "dikonfirmasi",
    "kututup": "ku tutup",
    "lalod": "lambat",
    "smpah": "sumpah",
    "blockir": "blokir",
    "jntuk": "untuk",
    "deceted": "terdeteksi",
    "mngerti": "mengerti",
    "sengklek": "rusak",
    "pirbiikin": "perbaiki",
    "kmarin": "kemarin",
    "num": "nomor",
    "ngilang": "menghilang",
    "rbet": "ribet",
    "nyepam": "spam",
    "telalu": "terlalu",
    "tabungann": "tabungan",
    "yahdik": "ya dik",
    "gins": "gini",
    "wes": "sudah",
    "pokokny": "pokoknya",
    "dyah": "dia",
    "sayaa": "saya",
    "tgal": "tanggal",
    "mbile": "mobile",
    "dl": "dulu",
    "laam": "lama",
    "udaah": "sudah",
    "krinsot": "tangkapan layar",
    "troble": "masalah",
    "blibet": "berbelit",
    "kaann": "kan",
    "harusny": "harusnya",
    "kcil": "kecil",
    "lbu": "ibu",
    "namin": "namun",
    "make": "pakai",
    "kmblikan": "kembalikan",
    "apka": "apakah",
    "merintah": "memerintah",
    "pkek": "pakai",
    "jarinan": "jaringan",
    "tarok": "taruh",
    "muslimaat": "muslimat",
    "kderible": "kredibel",
    "pantess": "pantas",
    "hinga": "hingga",
    "erorm": "eror",
    "veirfikasi": "verifikasi",
    "paakai": "pakai",
    "dwonload": "unduh",
    "mbnking": "m-banking",
    "nolong": "menolong",
    "bertivikasi": "verifikasi",
    "verfi": "verifikasi",
    "barakallahufiikum": "barakallah",
    "pilihanya": "pilihannya",
    "shott": "tangkapan layar",
    "bankig": "banking",
    "sanggub": "sanggup",
    "tergangu": "terganggu",
    "beuh": "aduh",
    "ngeliatin": "melihat",
    "anj": "anjing",
    "dann": "dan",
    "kterus": "terus",
    "muku": "mukanya",
    "kacaw": "kacau",
    "ntahlah": "entahlah",
    "kesell": "kesal",
    "mengunakan": "menggunakan",
    "sktr": "sekitar",
    "nanyakan": "menanyakan",
    "ttep": "tetap",
    "kekening": "rekening",
    "pedahal": "padahal",
    "digunakann": "digunakan",
    "perivikasinya": "verifikasinya",
    "gabikin": "tidak buat",
    "direpotin": "direpotkan",
    "bekurang": "berkurang",
    "byont": "byond",
    "gampai": "sampai",
    "ngelempar": "melempar",
    "aolikasi": "aplikasi",
    "aplini": "aplikasi ini",
    "fiturya": "fiturnya",
    "entahh": "entah",
    "kpla": "kepala",
    "suru": "suruh",
    "ker": "keren",
    "devlloper": "developer",
    "vedio": "video",
    "melancar": "melancarkan",
    "prinsipinya": "prinsipnya",
    "apliksii": "aplikasi",
    "mengecawakan": "mengecewakan",
    "teerima": "terima",
    "pndah": "pindah",
    "dajjal": "dajal",
    "ditingkatin": "ditingkatkan",
    "amet": "amat",
    "diperbaikan": "diperbaiki",
    "fluid": "lancar",
    "maky": "makanya",
    "cbg": "cabang",
    "expayet": "kedaluwarsa",
    "lollllll": "haha",
    "mabking": "m-banking",
    "keteranganya": "keterangannya",
    "kbnyakan": "kebanyakan",
    "nag": "nah",
    "bhs": "bahasa",
    "gunakannga": "gunakannya",
    "kalao": "kalau",
    "sekai": "sekali",
    "mantapl": "mantap",
    "musk": "masuk",
    "balesnya": "balasnya",
    "chp": "hp",
    "midah": "mudah",
    "tay": "tai",
    "lemodd": "lambat",
    "mbulet": "berbelit",
    "pemintaan": "permintaan",
    "pasilitas": "fasilitas",
    "kedepanya": "ke depannya",
    "verifasi": "verifikasi",
    "diakukan": "dilakukan",
    "bagiin": "bagikan",
    "gax": "tidak",
    "buriq": "buruk",
    "vertifaksi": "verifikasi",
    "tulisa": "tulisan",
    "puny": "punya",
    "ngerasa": "merasa",
    "seperri": "seperti",
    "benerin": "perbaiki",
    "selosinya": "solusinya",
    "yanh": "yang",
    "pum": "pun",
    "ssldo": "saldo",
    "cepaat": "cepat",
    "blass": "sama sekali",
    "pl": "tolong",
    "load": "muat",
    "amplikasiny": "aplikasinya",
    "kukenapa": "ku kenapa",
    "viripikasi": "verifikasi",
    "mudhorobah": "mudharabah",
    "sbeenrnya": "sebenarnya",
    "lemott": "lambat",
    "nua": "nya",
    "tangkot": "tangerang kota",
    "buktiin": "buktikan",
    "lenngkap": "lengkap",
    "ccok": "cocok",
    "titak": "tidak",
    "pegel": "pegal",
    "ktanya": "katanya",
    "kepercayaaan": "kepercayaan",
    "woyy": "woi",
    "krena": "karena",
    "haduhhh": "haduh",
    "seudah": "sesudah",
    "ujungny": "ujungnya",
    "cpt": "cepat",
    "serig": "sering",
    "bisah": "bisa",
    "woiiii": "woi",
    "gituin": "digitukan",
    "sitik": "sedikit",
    "intal": "instal",
    "devie": "device",
    "alhmdulilah": "alhamdulillah",
    "icon": "ikon",
    "okke": "oke",
    "idzin": "izin",
    "penyelesai": "penyelesaian",
    "ganiat": "tidak niat",
    "diperberbaiki": "diperbaiki",
    "miif": "maaf",
    "badmood": "suasana hati buruk",
    "halazim": "aladzim",
    "jadii": "jadi",
    "mempermudakan": "mempermudah",
    "kelurangan": "kekurangan",
    "kmaren": "kemarin",
    "ll": "akan",
    "wooooiii": "woi",
    "melakuka": "melakukan",
    "kepencet": "tertekan",
    "way": "cara",
    "nyaan": "nya",
    "kon": "kok",
    "inimah": "ini mah",
    "meresahkann": "meresahkan",
    "wajanya": "wajahnya",
    "kka": "kakak",
    "penuhin": "penuhi",
    "finger": "sidik jari",
    "record": "rekam",
    "tetiba": "tiba tiba",
    "hire": "pekerjakan",
    "trbru": "terbaru",
    "gilirang": "giliran",
    "jangn": "jangan",
    "iyah": "iya",
    "pidah": "pindah",
    "calk": "call",
    "dipakee": "dipakai",
    "verifikasin": "verifikasi",
    "cc": "call center",
    "woyyyy": "woi",
    "memudahkn": "memudahkan",
    "plsa": "pulsa",
    "siapi": "siapkan",
    "mabok": "mabuk",
    "trbantu": "terbantu",
    "gunanaya": "gunanya",
    "produck": "produk",
    "gamuncul": "tidak muncul",
    "dps": "deposito",
    "nelan": "menelan",
    "seprti": "seperti",
    "tetdaftar": "terdaftar",
    "saan": "saat",
    "ngeriview": "mengulas",
    "ssh": "susah",
    "dis": "di",
    "langsumg": "langsung",
    "nawarin": "menawarkan",
    "design": "desain",
    "hpsdh": "hp sudah",
    "urusi": "mengurus",
    "jugaa": "juga",
    "tinggalin": "tinggalkan",
    "wis": "sudah",
    "masukinnya": "memasukkannya",
    "pupops": "pop up",
    "sgala": "segala",
    "pwndaftaran": "pendaftaran",
    "trust": "percaya",
    "ditlp": "ditelepon",
    "gegayaan": "banyak gaya",
    "routed": "root",
    "perbiki": "perbaiki",
    "bankng": "banking",
    "font": "huruf",
    "dataa": "data",
    "ampir": "hampir",
    "amanan": "aman",
    "lainya": "lainnya",
    "gerakin": "gerakkan",
    "nyaudh": "nya sudah",
    "bsiiii": "bsi",
    "delaynya": "jedanya",
    "hapenya": "hpnya",
    "mobilekenapa": "mobile kenapa",
    "sampaihari": "sampai hari",
    "ulasanini": "ulasan ini",
    "kepotongpadahal": "terpotong padahal",
    "mandiriperbanyak": "mandiri perbanyak",
    "digunakanfiturnya": "digunakan fiturnya",
    "jugaaman": "juga aman",
    "dimenu": "di menu",
    "maksudnyamau": "maksudnya mau",
    "bagusmempermudah": "bagus mempermudah",
    "jaringanpun": "jaringan pun",
    "offlinejgn": "offline jangan",
    "biondterus": "byond terus",
    "benerlah": "benar lah",
    "lainini": "lain ini",
    "apkmeng": "aplikasi meng",
    "lgterpaksa": "lagi terpaksa",
    "digunakanlalu": "digunakan lalu",
    "gampangfiturnya": "gampang fiturnya",
    "mempersusahbeda": "mempersusah beda",
    "aksesnyamasyaallah": "aksesnya masyaallah",
    "gangguantolong": "gangguan tolong",
    "pertamakok": "pertama kok",
    "didalamnya": "di dalamnya",
    "verifikasivermuknya": "verifikasi vermuknya",
    "sedikitlah": "sedikit lah",
    "satusatu": "satu satu",
    "terpercayadata": "terpercaya data",
    "nyakadang": "nya kadang",
    "yamungkin": "ya mungkin",
    "sampaisampai": "sampai sampai",
    "kendalanyaini": "kendalanya ini",
    "bisaapa": "bisa apa",
    "pindahsering": "pindah sering",
    "assalamualaikumsaran": "assalamualaikum saran",
    "tolonglaaaah": "tolong lah",
    "syariahmau": "syariah mau",
    "layarrekaman": "layar rekaman",
    "donknambah": "dong nambah",
    "berhasilpadahal": "berhasil padahal",
    "tadibank": "tadi bank",
    "diperbaikipdhl": "diperbaiki padahal",
    "verifikasimelalui": "verifikasi melalui",
    "doangrobot": "doang robot",
    "outribet": "out ribet",
    "mobiledan": "mobile dan",
    "terakhirbug": "terakhir bug",
    "aplikasibetul": "aplikasi betul",
    "iklanmengganggu": "iklan mengganggu",
    "pahaminyaman": "pahami nyaman",
    "masuksaldo": "masuk saldo",
    "saldolha": "saldo lha",
    "ngelagterus": "macet terus",
    "temukanlbih": "temukan lebih",
    "negarabsi": "negara bsi",
    "prosesudah": "proses sudah",
    "bisaada": "bisa ada",
    "aplikasijujur": "aplikasi jujur",
    "suksesparah": "sukses parah",
    "sandinytolong": "sandinya tolong",
    "apapuntolong": "apapun tolong",
    "mmbntu": "membantu",
    "dsluruh": "di seluruh",
    "kbtuhan": "kebutuhan",
    "mkasih": "terima kasih",
    "nerima": "menerima",
    "lahhhhhhh": "lah",
    "udh": "sudah",
    "ga": "tidak",
}

slangwords = {**slang_general, **slang_in_df}


def fix_slangwords(text):
    """
    Normalize slang words in a text using a predefined slang dictionary.

    Each word in the input text is checked against a combined slang dictionary.
    If a match is found, the word is replaced with its formal equivalent.
    Words not found in the dictionary are left unchanged.

    Parameters
    ----------
    text : str
        Input text that may contain slang words.

    Returns
    -------
    str
        The processed text with slang words replaced by their formal equivalents.

    Notes
    -----
    This function relies on the global variable `slangwords`, which is a
    merged dictionary of `slang_general` and `slang_in_df`. The merging
    is done via ``{**slang_general, **slang_in_df}``, meaning keys in
    `slang_in_df` will override duplicate keys from `slang_general`.

    Examples
    --------
    >>> fix_slangwords("gw lg makan")
    'saya sedang makan'

    >>> fix_slangwords("dia udah pergi")
    'dia sudah pergi'
    """
    words = text.split()
    return " ".join(slangwords.get(word, word) for word in words)
